// Kevin O'Toole
// MIU 1304
// Project 2
// JSON Object

var json = {
	"recipe01": {
		"fname": ["First Name:", "Kevin"],
		"lname": ["Last Name:", "OToole"],
		"todaysDate": ["Date Added:", "11/12/13"],
		"family": ["Related:", "Yes"],
		"email": ["Email:", "kevin@kevin.com"],
		"group": ["Type of Recipe:", "Breakfast"],
		"range": ["Difficulty:", "8"],
		"whenCooked": ["When You Cook This:", "Easter"],
		"specify": ["Other Time:", "BBQ"],
		"time": ["Cooking Time:", "1 Hour"],
		"temperature": ["Cooking Temperature:", "350 Degrees"],
		"ingredients": ["Recipe Ingredients:", "Eggs, Milk, Butter"],
		"directions": ["Cooking Directions:", "Let Cook Slow"]
	},
	"recipe02": {
		"fname": ["First Name:", "James"],
		"lname": ["Last Name:", "OToole"],
		"todaysDate": ["Date Added:", "09/10/11"],
		"family": ["Related:", "Yes"],
		"email": ["Email:", "james@james.com"],
		"group": ["Type of Recipe:", "Drink"],
		"range": ["Difficulty:", "4"],
		"whenCooked": ["When You Cook This:", "Halloween"],
		"specify": ["Other Time:", "4th of July"],
		"time": ["Cooking Time:", "30 Mins"],
		"temperature": ["Cooking Temperature:", "Boil"],
		"ingredients": ["Recipe Ingredients:", "Jello, Water, Vodka"],
		"directions": ["Cooking Directions:", "Let set in fridge"]
	},
	"recipe03": {
		"fname": ["First Name:", "Kelly"],
		"lname": ["Last Name:", "OToole"],
		"todaysDate": ["Date Added:", "01/02/12"],
		"family": ["Related:", "Yes"],
		"email": ["Email:", "kelly@kelly.com"],
		"group": ["Type of Recipe:", "Dessert"],
		"range": ["Difficulty:", "6"],
		"whenCooked": ["When You Cook This:", "Birthdays"],
		"specify": ["Other Time:", "Anniversary"],
		"time": ["Cooking Time:", "1 Hour"],
		"temperature": ["Cooking Temperature:", "425 Degrees"],
		"ingredients": ["Recipe Ingredients:", "Cookie Mix"],
		"directions": ["Cooking Directions:", "Cook in oven then cool"]
	},
	"recipe04": {
		"fname": ["First Name:", "Jeanine"],
		"lname": ["Last Name:", "Esposito"],
		"todaysDate": ["Date Added:", "11/12/12"],
		"family": ["Related:", "Yes"],
		"email": ["Email:", "jeanine@jeanine.com"],
		"group": ["Type of Recipe:", "Appetizer"],
		"range": ["Difficulty:", "2"],
		"whenCooked": ["When You Cook This:", "Birthdays"],
		"specify": ["Other Time:", "BBQ"],
		"time": ["Cooking Time:", "1 Hour"],
		"temperature": ["Cooking Temperature:", "425 Degrees"],
		"ingredients": ["Recipe Ingredients:", "Biscuits, Hot Dogs"],
		"directions": ["Cooking Directions:", "Wrap and cook"]
	},
	"recipe05": {
		"fname": ["First Name:", "Susanne"],
		"lname": ["Last Name:", "Leone"],
		"todaysDate": ["Date Added:", "01/15/13"],
		"family": ["Related:", "Yes"],
		"email": ["Email:", "susanne@susanne.com"],
		"group": ["Type of Recipe:", "Dinner"],
		"range": ["Difficulty:", "6"],
		"whenCooked": ["When You Cook This:", "Christmas"],
		"specify": ["Other Time:", ""],
		"time": ["Cooking Time:", "3 Hour"],
		"temperature": ["Cooking Temperature:", "375 Degrees"],
		"ingredients": ["Recipe Ingredients:", "Noodles, Soup, Cheese"],
		"directions": ["Cooking Directions:", "Slow cook"]
	},
	"recipe06": {
		"fname": ["First Name:", "Hal"],
		"lname": ["Last Name:", "Sparks"],
		"todaysDate": ["Date Added:", "07/02/12"],
		"family": ["Related:", "No"],
		"email": ["Email:", "hal@sparks.com"],
		"group": ["Type of Recipe:", "Lunch"],
		"range": ["Difficulty:", "4"],
		"whenCooked": ["When You Cook This:", "New Years"],
		"specify": ["Other Time:", ""],
		"time": ["Cooking Time:", "5 minutes"],
		"temperature": ["Cooking Temperature:", "Microwave"],
		"ingredients": ["Recipe Ingredients:", "Ramen Noodles"],
		"directions": ["Cooking Directions:", "Nuke and eat"]
	},
	"recipe07": {
		"fname": ["First Name:", "Jordan"],
		"lname": ["Last Name:", "Roy"],
		"todaysDate": ["Date Added:", "03/12/13"],
		"family": ["Related:", "No"],
		"email": ["Email:", "jordan@roy.com"],
		"group": ["Type of Recipe:", "Dinner"],
		"range": ["Difficulty:", "3"],
		"whenCooked": ["When You Cook This:", "Birthdays"],
		"specify": ["Other Time:", ""],
		"time": ["Cooking Time:", "1 Hour"],
		"temperature": ["Cooking Temperature:", "415 Degrees"],
		"ingredients": ["Recipe Ingredients:", "Shrimp"],
		"directions": ["Cooking Directions:", "peel and eat"]
	},
	"recipe08": {
		"fname": ["First Name:", "Nick"],
		"lname": ["Last Name:", "Nite"],
		"todaysDate": ["Date Added:", "01/02/12"],
		"family": ["Related:", "No"],
		"email": ["Email:", "nick@nick.com"],
		"group": ["Type of Recipe:", "Dessert"],
		"range": ["Difficulty:", "9"],
		"whenCooked": ["When You Cook This:", "Birthdays"],
		"specify": ["Other Time:", ""],
		"time": ["Cooking Time:", "3 Hour"],
		"temperature": ["Cooking Temperature:", "375 Degrees"],
		"ingredients": ["Recipe Ingredients:", "Cake mix"],
		"directions": ["Cooking Directions:", "all from scratch"]
	},
	"recipe09": {
		"fname": ["First Name:", "Keira"],
		"lname": ["Last Name:", "Knight"],
		"todaysDate": ["Date Added:", "11/23/12"],
		"family": ["Related:", "No"],
		"email": ["Email:", "keira@keria.com"],
		"group": ["Type of Recipe:", "Breakfast"],
		"range": ["Difficulty:", "2"],
		"whenCooked": ["When You Cook This:", "Halloween"],
		"specify": ["Other Time:", ""],
		"time": ["Cooking Time:", "3 minutes"],
		"temperature": ["Cooking Temperature:", "Toaster"],
		"ingredients": ["Recipe Ingredients:", "Pop tarts"],
		"directions": ["Cooking Directions:", "Drizzle with icing"]
	},
	"recipe10": {
		"fname": ["First Name:", "Kesha"],
		"lname": ["Last Name:", "Lawrence"],
		"todaysDate": ["Date Added:", "01/02/12"],
		"family": ["Related:", "No"],
		"email": ["Email:", "kesha@kesha.com"],
		"group": ["Type of Recipe:", "Dessert"],
		"range": ["Difficulty:", "6"],
		"whenCooked": ["When You Cook This:", "Birthdays"],
		"specify": ["Other Time:", "Anniversary"],
		"time": ["Cooking Time:", "1 Hour"],
		"temperature": ["Cooking Temperature:", "425 Degrees"],
		"ingredients": ["Recipe Ingredients:", "Cookie from store"],
		"directions": ["Cooking Directions:", "Cook in oven then cool"]
	},
	"recipe11": {
		"fname": ["First Name:", "Jake"],
		"lname": ["Last Name:", "Johnson"],
		"todaysDate": ["Date Added:", "07/02/12"],
		"family": ["Related:", "No"],
		"email": ["Email:", "jake@jake.com"],
		"group": ["Type of Recipe:", "Appetizer"],
		"range": ["Difficulty:", "2"],
		"whenCooked": ["When You Cook This:", "Thanksgiving"],
		"specify": ["Other Time:", ""],
		"time": ["Cooking Time:", "1 Hour"],
		"temperature": ["Cooking Temperature:", "425 Degrees"],
		"ingredients": ["Recipe Ingredients:", "Cheese, Sala"],
		"directions": ["Cooking Directions:", "Melt then serve with chips"]
	},
	"recipe12": {
		"fname": ["First Name:", "Louis"],
		"lname": ["Last Name:", "Rasta"],
		"todaysDate": ["Date Added:", "12/14/12"],
		"family": ["Related:", "No"],
		"email": ["Email:", "louis@louis.com"],
		"group": ["Type of Recipe:", "Drink"],
		"range": ["Difficulty:", "1"],
		"whenCooked": ["When You Cook This:", "New Years"],
		"specify": ["Other Time:", ""],
		"time": ["Cooking Time:", "5 minutes"],
		"temperature": ["Cooking Temperature:", ""],
		"ingredients": ["Recipe Ingredients:", "Champagne, OJ"],
		"directions": ["Cooking Directions:", "Mix and serve"]
	},
	"recipe13": {
		"fname": ["First Name:", "Derrick"],
		"lname": ["Last Name:", "Dawson"],
		"todaysDate": ["Date Added:", "01/02/12"],
		"family": ["Related:", "No"],
		"email": ["Email:", "dd@dd.com"],
		"group": ["Type of Recipe:", "Drink"],
		"range": ["Difficulty:", "2"],
		"whenCooked": ["When You Cook This:", "Birthdays"],
		"specify": ["Other Time:", "Anniversary"],
		"time": ["Cooking Time:", "10 Mins"],
		"temperature": ["Cooking Temperature:", ""],
		"ingredients": ["Recipe Ingredients:", "Vokda, OJ"],
		"directions": ["Cooking Directions:", "Yummy!"]
	},
	"recipe14": {
		"fname": ["First Name:", "Sandy"],
		"lname": ["Last Name:", "Rice"],
		"todaysDate": ["Date Added:", "09/04/12"],
		"family": ["Related:", "Yes"],
		"email": ["Email:", "sandy@sandy.com"],
		"group": ["Type of Recipe:", "Dessert"],
		"range": ["Difficulty:", "7"],
		"whenCooked": ["When You Cook This:", "Birthdays"],
		"specify": ["Other Time:", ""],
		"time": ["Cooking Time:", "1 Hour"],
		"temperature": ["Cooking Temperature:", "425 Degrees"],
		"ingredients": ["Recipe Ingredients:", "Brownie Mix"],
		"directions": ["Cooking Directions:", "Cook in oven then cool"]
	},
	"recipe15": {
		"fname": ["First Name:", "Dane"],
		"lname": ["Last Name:", "OToole"],
		"todaysDate": ["Date Added:", "08/27/12"],
		"family": ["Related:", "Yes"],
		"email": ["Email:", "dane@dane.com"],
		"group": ["Type of Recipe:", "Lunch"],
		"range": ["Difficulty:", "2"],
		"whenCooked": ["When You Cook This:", "Other"],
		"specify": ["Other Time:", "Any Time"],
		"time": ["Cooking Time:", "5 minsutes"],
		"temperature": ["Cooking Temperature:", ""],
		"ingredients": ["Recipe Ingredients:", "PB&J"],
		"directions": ["Cooking Directions:", "delicious"]
	},
	"recipe16": {
		"fname": ["First Name:", "Greg"],
		"lname": ["Last Name:", "Michael"],
		"todaysDate": ["Date Added:", "10/20/12"],
		"family": ["Related:", "Yes"],
		"email": ["Email:", "greg@greg.com"],
		"group": ["Type of Recipe:", "Lunch"],
		"range": ["Difficulty:", "2"],
		"whenCooked": ["When You Cook This:", "Birthdays"],
		"specify": ["Other Time:", ""],
		"time": ["Cooking Time:", "1 Hour"],
		"temperature": ["Cooking Temperature:", "425 Degrees"],
		"ingredients": ["Recipe Ingredients:", "Cookie Mix"],
		"directions": ["Cooking Directions:", "Cook in oven then cool"]
	},
	"recipe17": {
		"fname": ["First Name:", "Joe"],
		"lname": ["Last Name:", "OToole"],
		"todaysDate": ["Date Added:", "02/04/12"],
		"family": ["Related:", "Yes"],
		"email": ["Email:", "joe@joe.com"],
		"group": ["Type of Recipe:", "Dinner"],
		"range": ["Difficulty:", "6"],
		"whenCooked": ["When You Cook This:", "Easter"],
		"specify": ["Other Time:", ""],
		"time": ["Cooking Time:", "1 Hour"],
		"temperature": ["Cooking Temperature:", "None"],
		"ingredients": ["Recipe Ingredients:", "Order Out"],
		"directions": ["Cooking Directions:", "Chinese Food"]
	},
	"recipe18": {
		"fname": ["First Name:", "Darren"],
		"lname": ["Last Name:", "OToole"],
		"todaysDate": ["Date Added:", "01/17/12"],
		"family": ["Related:", "Yes"],
		"email": ["Email:", "darren@darren.com"],
		"group": ["Type of Recipe:", "Dinner"],
		"range": ["Difficulty:", "10"],
		"whenCooked": ["When You Cook This:", "Halloween"],
		"specify": ["Other Time:", ""],
		"time": ["Cooking Time:", "22 mins"],
		"temperature": ["Cooking Temperature:", "Low Temp"],
		"ingredients": ["Recipe Ingredients:", "Meat, sauce"],
		"directions": ["Cooking Directions:", "slow cook"]
	},
	"recipe19": {
		"fname": ["First Name:", "Jessie"],
		"lname": ["Last Name:", "OToole"],
		"todaysDate": ["Date Added:", "01/22/12"],
		"family": ["Related:", "Yes"],
		"email": ["Email:", "jessie@jessie.com"],
		"group": ["Type of Recipe:", "Dessert"],
		"range": ["Difficulty:", "4"],
		"whenCooked": ["When You Cook This:", "Birthdays"],
		"specify": ["Other Time:", "Anniversary"],
		"time": ["Cooking Time:", "1 Hour"],
		"temperature": ["Cooking Temperature:", "425 Degrees"],
		"ingredients": ["Recipe Ingredients:", "Store Cookie Mix"],
		"directions": ["Cooking Directions:", "Cook in oven then cool"]
	},
	"recipe20": {
		"fname": ["First Name:", "Donnie"],
		"lname": ["Last Name:", "OToole"],
		"todaysDate": ["Date Added:", "01/02/12"],
		"family": ["Related:", "Yes"],
		"email": ["Email:", "donnie@donnie.com"],
		"group": ["Type of Recipe:", "Breakfast"],
		"range": ["Difficulty:", "2"],
		"whenCooked": ["When You Cook This:", "Christmas"],
		"specify": ["Other Time:", ""],
		"time": ["Cooking Time:", "10 Mins"],
		"temperature": ["Cooking Temperature:", "Hi-Med"],
		"ingredients": ["Recipe Ingredients:", "Water, Coffee"],
		"directions": ["Cooking Directions:", "Drin"]
	},
}